### ISSUE TITLE
Propagate Jersey request-scoped objects to child threads

### ISSUE THREAD

**Issue by krutsko** [xvik/dropwizard-guicey#49] opened 2018-05-08 06:17 UTC
In our code we often use Guice `ServletScopes.continueRequest` to transfer certain request-scoped objects to child processing threads from the main request thread. After upgrading to latest version of guicey we can't access some request-scoped objects on these child threads, e.g. `org.glassfish.jersey.server.ContaineRequest`. When trying to obtain it I got this error message:

```
! Caused by: java.lang.IllegalStateException: Not inside a request scope.
--
! at jersey.repackaged.com.google.common.base.Preconditions.checkState(Preconditions.java:173)
! at org.glassfish.jersey.process.internal.RequestScope.current(RequestScope.java:233)
! at org.glassfish.jersey.process.internal.RequestScope.findOrCreate(RequestScope.java:158)
! at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
````

We do pass this object to ServletScopes.continueRequest in the seed map so it should be present on the child threads. 

Looks like there had been a change in dropwizard-guicey after which the above objects were no longer registered in Guice's request scope.

https://github.com/xvik/dropwizard-guicey/commit/d2ebe0852877702546e2e86aa5f871456868c0d4#diff-b4b38e4be70d125313075099a02bf83c

Could you advise how to handle this?

**Comment by xvik** [comment] 2018-05-08 06:40
Interesting, I haven't thought about this case when applied the change and it's for sure a regression. I will fix that in the upcoming version (should be released in few weeks).

As a workaround, I could only suggest overriding bindings using [custom injector factory](http://xvik.github.io/dropwizard-guicey/4.1.0/guide/test/#overriding-beans). Something like this:

```java
public class FixedBindingsModule extends AbstractModule {

    private final Provider<Injector> provider;

    public FixedBindingsModule(final Provider<Injector> provider) {
        this.provider = provider;
    }

    @Override
    protected void configure() {
        jerseyToGuice(MultivaluedParameterExtractorProvider.class);
        jerseyToGuice(Application.class);
        jerseyToGuice(Providers.class);

        // request scoped objects, but hk will control their scope
        // must be used in guice only with Provider
        jerseyToGuice(UriInfo.class).in(RequestScoped.class);
        jerseyToGuice(ResourceInfo.class).in(RequestScoped.class);
        jerseyToGuice(HttpHeaders.class).in(RequestScoped.class);
        jerseyToGuice(SecurityContext.class).in(RequestScoped.class);
        jerseyToGuice(Request.class).in(RequestScoped.class);
        jerseyToGuice(ContainerRequest.class).in(RequestScoped.class);
        jerseyToGuice(AsyncContext.class).in(RequestScoped.class);
    }

    private ScopedBindingBuilder jerseyToGuice(final Class<?> type) {
        return JerseyBinding.bindJerseyComponent(binder(), provider, type);
    }
}

public class OverridingFactory implements InjectorFactory {

    private final Application app;

    public OverridingFactory(Application app) {
        this.app = app;
    }

    @Override
    public Injector createInjector(Stage stage, Iterable<? extends Module> modules) {
        return Guice.createInjector(
                Modules.override(modules)
                        .with(new FixedBindingsModule(new InjectorProvider(app)))
        );
    }
}

bootstrap.addBundle(GuiceBundle.builder()
                    .injectorFactory(new OverridingFactory(bootstrap.getApplication()))
                    .build())
```

Did not test it, but should work.

**Comment by krutsko** [comment] 2018-05-08 07:15
@xvik Thanks for a quick response!

I will try to override the bindings.

**Closed** 2018-05-08 09:03 UTC
Labels: bug

**Comment by xvik** [comment] 2018-05-08 09:17
It appears that the problem is a bit deeper and workaround above (by applying scoping annotation to jersey bindings) is not enough.  

Hk2 actually return proxies instead of raw instances and, even when guice is happy (with request scoped bean), hk proxy, called from different thread still checks hk scoping and fails (your stacktrace is actually hk scoping check).

To complete workaround you need to use fixed [JerseyComponentProvider](https://github.com/xvik/dropwizard-guicey/blob/daeee9e31a6c49dd65bd5d429baf7fec4a5adf6f/src/main/java/ru/vyarus/dropwizard/guice/module/jersey/support/JerseyComponentProvider.java#L35) or simply use [snapshot of current version](https://github.com/xvik/dropwizard-guicey#snapshots) (note that it use different artifact group)

**Comment by krutsko** [comment] 2018-05-08 09:25
OK, thank you!

Hope to get it released sooner than later.

**Comment by krutsko** [comment] 2018-05-31 06:46
@xvik can you make a release please?

**Comment by xvik** [comment] 2018-05-31 07:34
I'm finishing the last planned feature: configuration bindings (many people asked me about that). Initially, I did not expect to spend so many time updating generics-resolver (required for this feature), but it also almost ready. If I knew it would take so much time, I would exclude it from release scope, but now it's too late (time already spent).

There are also pre-release tasks (like documentation update, examples check and overall final review) which will take some time too. Overall, I doubt it would take less than a week to release, sorry.

**Comment by xvik** [comment] 2018-06-25 16:47
New version finally [released](http://xvik.github.io/dropwizard-guicey/4.2.0/)
