### ISSUE TITLE
NPE when locating JpaPersistService

### ISSUE THREAD

**Issue by OndraZizka** [xvik/dropwizard-guicey#50] opened 2018-06-07 08:55 UTC
I have replaced `dropwizard-guice` with `dropwizard-guicey` and it seems it can't inject JpaPersistService.
I got a lot of errors like this:

 335) Error in custom provider, java.lang.NullPointerException
  while locating com.google.inject.persist.jpa.JpaPersistService

Is there something extra I need to do to make this work?
Other injection seems to work, e.g. the configuration classes and our specific module adding @Named values.

Dropwizard 1.3.1,
`dropwizard-guicey` 4.1.0,
Guice 4.1.0,
guice-persist  4.1.0,

```
Caused by: java.lang.NullPointerException
        at com.google.inject.persist.jpa.JpaPersistService.begin(JpaPersistService.java:77)
        at com.google.inject.persist.jpa.JpaPersistService.get(JpaPersistService.java:57)
        at com.google.inject.persist.jpa.JpaPersistService.get(JpaPersistService.java:41)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
        at com...csl.persistence.dao.JpaDao.getCriteriaBuilder(JpaDao.java:144)
        at com...csa.persistence.search.AbstractSearcher.<init>(AbstractSearcher.java:30)
        at com..csa.persistence.search.impl.LegacyAttendanceSearcher.<init>(LegacyAttendanceSearcher.java:27)
        at com...csa.persistence.search.impl.LegacyAttendanceSearcher$$FastClassByGuice$$3ce32f21.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ExposedKeyFactory.get(ExposedKeyFactory.java:54)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at ru.vyarus.dropwizard.guice.injector.DefaultInjectorFactory.createInjector(DefaultInjectorFactory.java:20)
        at ru.vyarus.dropwizard.guice.GuiceBundle.createInjector(GuiceBundle.java:191)
        at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:138)
        at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:93)
        at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
```

**Comment by xvik** [comment] 2018-06-07 09:15
No, you don't need anything else: it's pure guice, no magic. 
99,99% the problem is in your code :)
If you show me some code I would be able to help you finding the actual reason.

Also, you can look [hiberante exmaple](https://github.com/xvik/dropwizard-guicey-examples/tree/master/hibernate). It doesn't use guice-persist (so you will not be able to use transaction annotations), but, as it use dropwizard hibernate module it's better integrated with dropwizard

**Comment by OndraZizka** [comment] 2018-06-07 09:59
Which part of the code is relevant? Basically, I left the code almost intact. So I assume if it worked with d-guice, it could with d-guicey. Is there a migration guide?

**Comment by xvik** [comment] 2018-06-07 10:44
You obviously start using jpa PersistService before it's initialization (PersistService.start()):
JpaPersistService#entityManager:77 is inside transaction start (UnitOfWork#begin())
and appeared as part of EntityManager resolution: JpaPersistService#get():57.

So something requested direct injection of EntityManager, while persistence is not yet ready.

Guicey [force singletons on resources (rest)](http://xvik.github.io/dropwizard-guicey/4.1.0/installers/resource/) and also guicey binds all extensions in guice context so they start together with context (and not on first usage). Most likely, before, your resources were request-scoped and so created long after guice initialization (after persistence start).

The fix is to use `Provider<EntityManager>` instead of direct `EntityManager`. [Other workarounds](http://xvik.github.io/dropwizard-guicey/4.1.0/guide/lifecycle/#problematic-cases):
* annotate resources with @LazyBinding - this will avoid binding into guice context and resources will be initialized later when hk call them (jersey initialization).
* use @HK2Managed on resources to delegate management to hk2 (so resources will be created after guice start), but, in this case, you will not be able to use guice aop.

Current guicey trunk already supports prototype scoped resources, but this version is not released yet. And I'm still not advise to use prototype scope on resources because it's a waste of resources.

**Comment by OndraZizka** [comment] 2018-06-07 11:35
Thanks a lot for the explicit explanation.
In the meantime we have a change in a PR that uses `Provider`, so I'll rebase and see if it fixes.

By the way, Guice has `build(Scope.DEVELOPMENT)` which makes Guice start the Singletons lazily rather than in advance, which is the solution my colleague took in that PR where `dw-guice` is still used. Will that work with `dw-guicey` too?

**Comment by xvik** [comment] 2018-06-07 13:49
Yes, of course, you can set development stage in [bundle builder](http://xvik.github.io/dropwizard-guicey/4.1.0/guide/configuration/#stage).

**Closed** 2018-06-19 03:28 UTC
